using UnityEngine;

[CreateAssetMenu(fileName = "Database", menuName ="MiniGameDataBase")]
public class MiniGameDataBase : ScriptableObject
{
    public Sprite a_ca_on;
    public Sprite a_ca_off;
    public Sprite a_on;
    public Sprite a_off;
    public Sprite b_on;
    public Sprite b_off;
    public Sprite c_on;
    public Sprite c_off;
    public Sprite d_on;
    public Sprite d_of;
    public Sprite e_ca_on;
    public Sprite e_ca_off;
    public Sprite e_on;
    public Sprite e_off;
    public Sprite f_on;
    public Sprite f_off;
    public Sprite g_on;
    public Sprite g_off;
    public Sprite h_on;
    public Sprite h_off;
    public Sprite i_ca_on;
    public Sprite i_ca_off;
    public Sprite i_on;
    public Sprite i_off;
    public Sprite j_on;
    public Sprite j_off;
    public Sprite k_on;
    public Sprite k_off;
    public Sprite l_on;
    public Sprite l_off;
    public Sprite m_on;
    public Sprite m_off;
    public Sprite n_on;
    public Sprite n_off;
    public Sprite o_ca_on;
    public Sprite o_ca_off;
    public Sprite o_on;
    public Sprite o_off;
    public Sprite p_on;
    public Sprite p_off;
    public Sprite q_on;
    public Sprite q_off;
    public Sprite r_on;
    public Sprite r_off;
    public Sprite s_on;
    public Sprite s_off;
    public Sprite t_on;
    public Sprite t_off;
    public Sprite u_ca_on;
    public Sprite u_ca_off;
    public Sprite u_on;
    public Sprite u_off;
    public Sprite v_on;
    public Sprite v_off;
    public Sprite w_on;
    public Sprite w_off;
    public Sprite x_on;
    public Sprite x_off;
    public Sprite y_on;
    public Sprite y_off;
    public Sprite z_on;
    public Sprite z_off;
}
